# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iPhoneHTTPServerToJs' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iPhoneHTTPServerToJs
  pod 'SSZipArchive'
  pod 'AFNetworking'
  pod 'CocoaHTTPServer'
  target 'iPhoneHTTPServerToJsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iPhoneHTTPServerToJsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
